(ns clojure-pike-regex.test.core
  (:use [clojure-pike-regex.core])
  (:use [clojure.test]))

(deftest match-test
  (is (match "" ""))
  (is (match "" "a"))
  (is (match "" "abc"))
  (is (match "a" "a"))
  (is (match "a" "ab"))
  (is (match "b" "ab"))
  (is (match "b" "abc"))
  (is (match "c" "abc"))
  (is (not (match "a" "")))
  (is (not (match "d" "abc")))
  (is (match "ab" "ab"))
  (is (match "ab" "abc"))
  (is (match "bc" "abc"))
  (is (not (match "cd" "abc")))
  (is (match "^a" "a"))
  (is (match "^a" "ab"))
  (is (not (match "^a" "")))
  (is (not (match "^b" "a")))
  (is (not (match "^b" "ab")))
  (is (match "^ab" "ab"))
  (is (match "^ab" "abc"))
  (is (match "a$" "a"))
  (is (match "b$" "ab"))
  (is (not (match "a$" "")))
  (is (not (match "b$" "a")))
  (is (not (match "a$" "ab")))
  (is (match "ab$" "ab"))
  (is (match "bc$" "abc"))
  (is (not (match "." "")))
  (is (match "^ab$" "ab"))
  (is (not (match "^ab$" "abc")))
  (is (not (match "^bc$" "abc")))
  (is (match "." "a"))
  (is (match "." "ab"))
  (is (match "a." "ab"))
  (is (match ".b" "ab"))
  (is (not (match "a." "a")))
  (is (match "a.c" "abc"))
  (is (match ".." "ab"))
  (is (match "..c" "abc"))
  (is (match "a..d" "abcd"))
  (is (match "a.c.e" "abcde"))
  (is (match "a.c.e" "abcde"))
  (is (not (match "..." "ab")))
  (is (match "^." "a"))
  (is (match ".$" "a"))
  (is (match "^.$" "a"))
  (is (match "^..$" "ab"))
  (is (not (match "^.$" "ab")))
  (is (not (match "*" "")))
  (is (not (match "*" "a")))
  (is (match "a*" ""))
  (is (match "a*" "a"))
  (is (match "a*" "aa"))
  (is (match "a*" "ab"))
  (is (match "a*" "b"))
  (is (match ".*" "a"))
  (is (match ".*" "abc"))
  (is (match "ab*" "abb"))
  (is (match "^a*" "a"))
  (is (match "^a*" "ab"))
  (is (match "^.*" "a"))
  (is (match "^.*" "ab"))
  (is (match "a*$" "a"))
  (is (match "ab*$" "a"))
  (is (match "ab*$" "ab"))
  (is (match "^.*" "a"))
  (is (match "^.*" "ab"))
  (is (match "^a*$" "a"))
  (is (match "^ab*$" "a"))
  (is (match "^.*$" "a")))